/*
    Weave (Web-based Analysis and Visualization Environment)
    Copyright (C) 2008-2011 University of Massachusetts Lowell

    This file is a part of Weave.

    Weave is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License, Version 3,
    as published by the Free Software Foundation.

    Weave is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Weave.  If not, see <http://www.gnu.org/licenses/>.
*/

package weave.geometrystream;

import java.util.HashMap;
import java.util.LinkedList;

/**
 * @author adufilie
 */
public class VertexMap
{
	/**
	 * This Map is used as a hash lookup for CombinedPoint objects.
	 * Using this Map, we can look up a CombinedPoint object and add new vertex IDs to it.
	 */
	private final HashMap<CombinedPoint, CombinedPoint> map = new HashMap<CombinedPoint, CombinedPoint>();
	
	private final LinkedList<PartMarker> partMarkers = new LinkedList<PartMarker>();

	public int getCombinedPointCount()
	{
		return map.size();
	}
	
	private int totalStreamSize = 0;
	public int getTotalStreamSize()
	{
		return totalStreamSize;
	}
	
	public void addPartMarker(int shapeID, int firstVertexID, int chainLength, Bounds2D partBounds)
	{
		PartMarker pm = new PartMarker(shapeID, firstVertexID, chainLength, partBounds);
		partMarkers.add(pm);
		totalStreamSize += pm.getStreamSize();
	}
	
	private final CombinedPoint searchPoint = new CombinedPoint(Double.NaN, Double.NaN);
	
	/**
	 * This will call CombinedPoint.addPoint() on a CombinedPoint object matching
	 * the x,y coordinates of the given vertex.
	 * @param shapeID The ID of the shape in which the vertex exists.
	 * @param point Information about a vertex in the specified shape.
	 * @param maxImportance Maximum possible importance to use in place of VertexChainLink.IMPORTANCE_REQUIRED
	 */
	public void addPoint(int shapeID, VertexChainLink point, double maxImportance, Bounds2D partBounds)
	{
		// get a new CombinedPoint object to be used when a
		searchPoint.x = point.x;
		searchPoint.y = point.y;

		// check the hash map for a matching CombinedPoint object
		CombinedPoint existingCombinedPoint = map.get(searchPoint);
		if (existingCombinedPoint == null)
		{
			CombinedPoint newCombinedPoint = new CombinedPoint(point.x, point.y);
			// hash map doesn't have a matching CombinedPoint object, so save the new one
			map.put(newCombinedPoint, newCombinedPoint);
			totalStreamSize += newCombinedPoint.getStreamSize(); // include new CombinedPoint in total stream size
			existingCombinedPoint = newCombinedPoint;
		}

		// add a VertexIdentifier to the existing CombinedPoint and update total stream size
		totalStreamSize -= existingCombinedPoint.getStreamSize();
		existingCombinedPoint.addPoint(shapeID, point, partBounds);
		totalStreamSize += existingCombinedPoint.getStreamSize();
		
		// update importance
		double importance = point.importance;
		if (importance == VertexChainLink.IMPORTANCE_REQUIRED)
			importance = maxImportance;
		existingCombinedPoint.updateMinimumImportance(importance);
	}

	/**
	 * This function retrieves all the CombinedPoint objects that have been generated by calls to addPoint().
	 * @return A Vector of CombinedPoint objects.
	 */
	public LinkedList<IStreamObject> getStreamObjects()
	{
		LinkedList<IStreamObject> result = new LinkedList<IStreamObject>(map.values());
		result.addAll(partMarkers);
		return result;
	}

	/**
	 * This returns all CombinedPoint instances this object is using back to the CombinedPoint object pool.
	 */
	public void clear()
	{
		map.clear();
		partMarkers.clear();
		totalStreamSize = 0;
	}
}
