/**
 * This function modifies a session state object generated by Weave by inserting a value at a specified path.
 * @param stateToModify The session state object to modify.
 * @param path A series of object names in the Weave session state hierarchy.
 * @param value The replacement session state to insert at the given path.
 * @return true on success, false on failure
 */
function modifySessionState(stateToModify, path, value)
{
    if (path.length == 0)
        return false
    var property = path[0];
    path = path.slice(1);
    if (stateToModify.constructor == Array)
    {
        for each (var dynamicState in stateToModify)
        {
            if (property == dynamicState.objectName)
            {
                if (path.length)
                    return modifySessionState(dynamicState.sessionState, path, value);
                dynamicState.sessionState = value;
                return true;
            }
        }
        return false;
    }
    if (path.length)
        return modifySessionState(stateToModify[property], path, value)
    stateToModify[property] = value;
    return true;
}
