/**
 * Generated by Apache Flex Cross-Compiler from weavejs\utils\Utils.as
 * weavejs.utils.Utils
 *
 * @fileoverview
 *
 * @suppress {checkTypes}
 */

goog.provide('weavejs.utils.Utils');



/**
 * @constructor
 */
weavejs.utils.Utils = function() {
};


/**
 * @export
 * @const
 * @type {Object}
 */
weavejs.utils.Utils.Map = function() {
  return this['Map'];
}.apply(null);


/**
 * @export
 * @const
 * @type {Object}
 */
weavejs.utils.Utils.WeakMap = function() {
  return this['WeakMap'];
}.apply(null);


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
weavejs.utils.Utils.prototype.FLEXJS_CLASS_INFO = { names: [{ name: 'Utils', qName: 'weavejs.utils.Utils'}] };
