/**
 * Generated by Apache Flex Cross-Compiler from weavejs\api\core\ICallbackCollection.as
 * weavejs.api.core.ICallbackCollection
 *
 * @fileoverview
 *
 * @suppress {checkTypes}
 */

goog.provide('weavejs.api.core.ICallbackCollection');

goog.require('weavejs.api.core.ILinkableObject');



/**
 * @interface
 * @extends {weavejs.api.core.ILinkableObject}
 */
weavejs.api.core.ICallbackCollection = function() {
};
weavejs.api.core.ICallbackCollection.prototype.addImmediateCallback = function(relevantContext, callback, runCallbackNow, alwaysCallLast) {
};
weavejs.api.core.ICallbackCollection.prototype.addGroupedCallback = function(relevantContext, groupedCallback, triggerCallbackNow) {
};
weavejs.api.core.ICallbackCollection.prototype.addDisposeCallback = function(relevantContext, callback) {
};
weavejs.api.core.ICallbackCollection.prototype.removeCallback = function(callback) {
};
weavejs.api.core.ICallbackCollection.prototype.triggerCallbacks = function() {
};
/**  * @type {number}
 */weavejs.api.core.ICallbackCollection.prototype.triggerCounter;
weavejs.api.core.ICallbackCollection.prototype.delayCallbacks = function() {
};
weavejs.api.core.ICallbackCollection.prototype.resumeCallbacks = function() {
};


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
weavejs.api.core.ICallbackCollection.prototype.FLEXJS_CLASS_INFO = { names: [{ name: 'ICallbackCollection', qName: 'weavejs.api.core.ICallbackCollection'}], interfaces: [weavejs.api.core.ILinkableObject] };
