/**
 * Generated by Apache Flex Cross-Compiler from weavejs\api\core\IChildListCallbackInterface.as
 * weavejs.api.core.IChildListCallbackInterface
 *
 * @fileoverview
 *
 * @suppress {checkTypes}
 */

goog.provide('weavejs.api.core.IChildListCallbackInterface');

goog.require('weavejs.api.core.ICallbackCollection');
goog.require('weavejs.api.core.ILinkableObject');



/**
 * @interface
 * @extends {weavejs.api.core.ICallbackCollection}
 */
weavejs.api.core.IChildListCallbackInterface = function() {
};
/**  * @type {weavejs.api.core.ILinkableObject}
 */weavejs.api.core.IChildListCallbackInterface.prototype.lastObjectAdded;


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
weavejs.api.core.IChildListCallbackInterface.prototype.FLEXJS_CLASS_INFO = { names: [{ name: 'IChildListCallbackInterface', qName: 'weavejs.api.core.IChildListCallbackInterface'}], interfaces: [weavejs.api.core.ICallbackCollection] };
