/**
 * Generated by Apache Flex Cross-Compiler from weavejs\api\core\IClassRegistry.as
 * weavejs.api.core.IClassRegistry
 *
 * @fileoverview
 *
 * @suppress {checkTypes}
 */

goog.provide('weavejs.api.core.IClassRegistry');



/**
 * @interface
 */
weavejs.api.core.IClassRegistry = function() {
};
weavejs.api.core.IClassRegistry.prototype.registerSingletonImplementation = function(theInterface, theImplementation) {
};
weavejs.api.core.IClassRegistry.prototype.getSingletonImplementation = function(theInterface) {
};
weavejs.api.core.IClassRegistry.prototype.getSingletonInstance = function(theInterface) {
};
weavejs.api.core.IClassRegistry.prototype.registerImplementation = function(theInterface, theImplementation, displayName) {
};
weavejs.api.core.IClassRegistry.prototype.getImplementations = function(theInterface) {
};
weavejs.api.core.IClassRegistry.prototype.getDisplayName = function(theImplementation) {
};


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
weavejs.api.core.IClassRegistry.prototype.FLEXJS_CLASS_INFO = { names: [{ name: 'IClassRegistry', qName: 'weavejs.api.core.IClassRegistry'}] };
