/**
 * Generated by Apache Flex Cross-Compiler from weavejs\api\core\IDisposableObject.as
 * weavejs.api.core.IDisposableObject
 *
 * @fileoverview
 *
 * @suppress {checkTypes}
 */

goog.provide('weavejs.api.core.IDisposableObject');



/**
 * @interface
 */
weavejs.api.core.IDisposableObject = function() {
};
weavejs.api.core.IDisposableObject.prototype.dispose = function() {
};


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
weavejs.api.core.IDisposableObject.prototype.FLEXJS_CLASS_INFO = { names: [{ name: 'IDisposableObject', qName: 'weavejs.api.core.IDisposableObject'}] };
