/**
 * Generated by Apache Flex Cross-Compiler from weavejs\api\core\IExternalSessionStateInterface.as
 * weavejs.api.core.IExternalSessionStateInterface
 *
 * @fileoverview
 *
 * @suppress {checkTypes}
 */

goog.provide('weavejs.api.core.IExternalSessionStateInterface');



/**
 * @interface
 */
weavejs.api.core.IExternalSessionStateInterface = function() {
};


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
weavejs.api.core.IExternalSessionStateInterface.prototype.FLEXJS_CLASS_INFO = { names: [{ name: 'IExternalSessionStateInterface', qName: 'weavejs.api.core.IExternalSessionStateInterface'}] };
