/**
 * Generated by Apache Flex Cross-Compiler from weavejs\api\core\ILinkableObjectWithNewProperties.as
 * weavejs.api.core.ILinkableObjectWithNewProperties
 *
 * @fileoverview
 *
 * @suppress {checkTypes}
 */

goog.provide('weavejs.api.core.ILinkableObjectWithNewProperties');

goog.require('weavejs.api.core.ILinkableObject');



/**
 * @interface
 * @extends {weavejs.api.core.ILinkableObject}
 */
weavejs.api.core.ILinkableObjectWithNewProperties = function() {
};
weavejs.api.core.ILinkableObjectWithNewProperties.prototype.handleMissingSessionStateProperty = function(newState, property) {
};


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
weavejs.api.core.ILinkableObjectWithNewProperties.prototype.FLEXJS_CLASS_INFO = { names: [{ name: 'ILinkableObjectWithNewProperties', qName: 'weavejs.api.core.ILinkableObjectWithNewProperties'}], interfaces: [weavejs.api.core.ILinkableObject] };
