/**
 * Generated by Apache Flex Cross-Compiler from weavejs\api\core\ILinkableDisplayObject.as
 * weavejs.api.core.ILinkableDisplayObject
 *
 * @fileoverview
 *
 * @suppress {checkTypes}
 */

goog.provide('weavejs.api.core.ILinkableDisplayObject');

goog.require('weavejs.api.core.ILinkableObject');



/**
 * @interface
 * @extends {weavejs.api.core.ILinkableObject}
 */
weavejs.api.core.ILinkableDisplayObject = function() {
};
/**  * @type {flash.display.DisplayObjectContainer}
 */weavejs.api.core.ILinkableDisplayObject.prototype.parent;


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
weavejs.api.core.ILinkableDisplayObject.prototype.FLEXJS_CLASS_INFO = { names: [{ name: 'ILinkableDisplayObject', qName: 'weavejs.api.core.ILinkableDisplayObject'}], interfaces: [weavejs.api.core.ILinkableObject] };
