/**
 * Generated by Apache Flex Cross-Compiler from weavejs\api\core\ILinkableCompositeObject.as
 * weavejs.api.core.ILinkableCompositeObject
 *
 * @fileoverview
 *
 * @suppress {checkTypes}
 */

goog.provide('weavejs.api.core.ILinkableCompositeObject');

goog.require('weavejs.api.core.ILinkableObject');



/**
 * @interface
 * @extends {weavejs.api.core.ILinkableObject}
 */
weavejs.api.core.ILinkableCompositeObject = function() {
};
weavejs.api.core.ILinkableCompositeObject.prototype.getSessionState = function() {
};
weavejs.api.core.ILinkableCompositeObject.prototype.setSessionState = function(newState, removeMissingDynamicObjects) {
};


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
weavejs.api.core.ILinkableCompositeObject.prototype.FLEXJS_CLASS_INFO = { names: [{ name: 'ILinkableCompositeObject', qName: 'weavejs.api.core.ILinkableCompositeObject'}], interfaces: [weavejs.api.core.ILinkableObject] };
