/**
 * Generated by Apache Flex Cross-Compiler from weavejs\api\core\ILinkableHashMap.as
 * weavejs.api.core.ILinkableHashMap
 *
 * @fileoverview
 *
 * @suppress {checkTypes}
 */

goog.provide('weavejs.api.core.ILinkableHashMap');

goog.require('weavejs.api.core.IChildListCallbackInterface');
goog.require('weavejs.api.core.ILinkableCompositeObject');
goog.require('weavejs.api.core.ILinkableObject');



/**
 * @interface
 * @extends {weavejs.api.core.ILinkableCompositeObject}
 */
weavejs.api.core.ILinkableHashMap = function() {
};
/**  * @type {Object}
 */weavejs.api.core.ILinkableHashMap.prototype.typeRestriction;
weavejs.api.core.ILinkableHashMap.prototype.setNameOrder = function(newOrder) {
};
weavejs.api.core.ILinkableHashMap.prototype.getNames = function(filter) {
};
weavejs.api.core.ILinkableHashMap.prototype.getObjects = function(filter) {
};
weavejs.api.core.ILinkableHashMap.prototype.getName = function(object) {
};
weavejs.api.core.ILinkableHashMap.prototype.getObject = function(name) {
};
weavejs.api.core.ILinkableHashMap.prototype.requestObject = function(name, classDef, lockObject) {
};
weavejs.api.core.ILinkableHashMap.prototype.requestObjectCopy = function(name, objectToCopy) {
};
weavejs.api.core.ILinkableHashMap.prototype.renameObject = function(oldName, newName) {
};
weavejs.api.core.ILinkableHashMap.prototype.objectIsLocked = function(name) {
};
weavejs.api.core.ILinkableHashMap.prototype.removeObject = function(name) {
};
weavejs.api.core.ILinkableHashMap.prototype.removeAllObjects = function() {
};
weavejs.api.core.ILinkableHashMap.prototype.generateUniqueName = function(baseName) {
};


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
weavejs.api.core.ILinkableHashMap.prototype.FLEXJS_CLASS_INFO = { names: [{ name: 'ILinkableHashMap', qName: 'weavejs.api.core.ILinkableHashMap'}], interfaces: [weavejs.api.core.ILinkableCompositeObject] };
