/**
 * Generated by Apache Flex Cross-Compiler from weavejs\api\core\ILinkableObject.as
 * weavejs.api.core.ILinkableObject
 *
 * @fileoverview
 *
 * @suppress {checkTypes}
 */

goog.provide('weavejs.api.core.ILinkableObject');



/**
 * @interface
 */
weavejs.api.core.ILinkableObject = function() {
};


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
weavejs.api.core.ILinkableObject.prototype.FLEXJS_CLASS_INFO = { names: [{ name: 'ILinkableObject', qName: 'weavejs.api.core.ILinkableObject'}] };
