/**
 * Generated by Apache Flex Cross-Compiler from weavejs\api\core\ILinkableObjectWithBusyStatus.as
 * weavejs.api.core.ILinkableObjectWithBusyStatus
 *
 * @fileoverview
 *
 * @suppress {checkTypes}
 */

goog.provide('weavejs.api.core.ILinkableObjectWithBusyStatus');

goog.require('weavejs.api.core.ILinkableObject');



/**
 * @interface
 * @extends {weavejs.api.core.ILinkableObject}
 */
weavejs.api.core.ILinkableObjectWithBusyStatus = function() {
};
weavejs.api.core.ILinkableObjectWithBusyStatus.prototype.isBusy = function() {
};


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
weavejs.api.core.ILinkableObjectWithBusyStatus.prototype.FLEXJS_CLASS_INFO = { names: [{ name: 'ILinkableObjectWithBusyStatus', qName: 'weavejs.api.core.ILinkableObjectWithBusyStatus'}], interfaces: [weavejs.api.core.ILinkableObject] };
