/**
 * Generated by Apache Flex Cross-Compiler from weavejs\api\core\ILinkableDynamicObject.as
 * weavejs.api.core.ILinkableDynamicObject
 *
 * @fileoverview
 *
 * @suppress {checkTypes}
 */

goog.provide('weavejs.api.core.ILinkableDynamicObject');

goog.require('weavejs.api.core.ILinkableCompositeObject');
goog.require('weavejs.api.core.ILinkableObject');



/**
 * @interface
 * @extends {weavejs.api.core.ILinkableCompositeObject}
 */
weavejs.api.core.ILinkableDynamicObject = function() {
};
/**  * @type {weavejs.api.core.ILinkableObject}
 */weavejs.api.core.ILinkableDynamicObject.prototype.internalObject;
weavejs.api.core.ILinkableDynamicObject.prototype.requestGlobalObject = function(name, objectType, lockObject) {
};
weavejs.api.core.ILinkableDynamicObject.prototype.requestLocalObject = function(objectType, lockObject) {
};
weavejs.api.core.ILinkableDynamicObject.prototype.requestLocalObjectCopy = function(objectToCopy) {
};
weavejs.api.core.ILinkableDynamicObject.prototype.lock = function() {
};
weavejs.api.core.ILinkableDynamicObject.prototype.removeObject = function() {
};


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
weavejs.api.core.ILinkableDynamicObject.prototype.FLEXJS_CLASS_INFO = { names: [{ name: 'ILinkableDynamicObject', qName: 'weavejs.api.core.ILinkableDynamicObject'}], interfaces: [weavejs.api.core.ILinkableCompositeObject] };
