/**
 * Generated by Apache Flex Cross-Compiler from weavejs\api\core\ILinkableVariable.as
 * weavejs.api.core.ILinkableVariable
 *
 * @fileoverview
 *
 * @suppress {checkTypes}
 */

goog.provide('weavejs.api.core.ILinkableVariable');

goog.require('weavejs.api.core.ILinkableObject');



/**
 * @interface
 * @extends {weavejs.api.core.ILinkableObject}
 */
weavejs.api.core.ILinkableVariable = function() {
};
weavejs.api.core.ILinkableVariable.prototype.getSessionState = function() {
};
weavejs.api.core.ILinkableVariable.prototype.setSessionState = function(value) {
};


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
weavejs.api.core.ILinkableVariable.prototype.FLEXJS_CLASS_INFO = { names: [{ name: 'ILinkableVariable', qName: 'weavejs.api.core.ILinkableVariable'}], interfaces: [weavejs.api.core.ILinkableObject] };
