/**
 * Generated by Apache Flex Cross-Compiler from weavejs\api\core\ILocaleManager.as
 * weavejs.api.core.ILocaleManager
 *
 * @fileoverview
 *
 * @suppress {checkTypes}
 */

goog.provide('weavejs.api.core.ILocaleManager');



/**
 * @interface
 */
weavejs.api.core.ILocaleManager = function() {
};
weavejs.api.core.ILocaleManager.prototype.getAllLocales = function() {
};
weavejs.api.core.ILocaleManager.prototype.getAllLocalizations = function() {
};
weavejs.api.core.ILocaleManager.prototype.importLocalizations = function(newData) {
};
weavejs.api.core.ILocaleManager.prototype.registerTranslation = function(originalText, locale, localizedText) {
};
weavejs.api.core.ILocaleManager.prototype.clearAllLocalizations = function() {
};
weavejs.api.core.ILocaleManager.prototype.removeEntry = function(originalText) {
};
weavejs.api.core.ILocaleManager.prototype.getLocale = function() {
};
weavejs.api.core.ILocaleManager.prototype.setLocale = function(locale) {
};
weavejs.api.core.ILocaleManager.prototype.initializeLocale = function(locale) {
};
weavejs.api.core.ILocaleManager.prototype.localize = function(text, locale) {
};


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
weavejs.api.core.ILocaleManager.prototype.FLEXJS_CLASS_INFO = { names: [{ name: 'ILocaleManager', qName: 'weavejs.api.core.ILocaleManager'}] };
