/**
 * Generated by Apache Flex Cross-Compiler from weavejs\api\core\IProgressIndicator.as
 * weavejs.api.core.IProgressIndicator
 *
 * @fileoverview
 *
 * @suppress {checkTypes}
 */

goog.provide('weavejs.api.core.IProgressIndicator');

goog.require('weavejs.api.core.ILinkableObject');



/**
 * @interface
 * @extends {weavejs.api.core.ILinkableObject}
 */
weavejs.api.core.IProgressIndicator = function() {
};
weavejs.api.core.IProgressIndicator.prototype.getTaskCount = function() {
};
weavejs.api.core.IProgressIndicator.prototype.addTask = function(taskToken, busyObject, description) {
};
weavejs.api.core.IProgressIndicator.prototype.hasTask = function(taskToken) {
};
weavejs.api.core.IProgressIndicator.prototype.updateTask = function(taskToken, progress) {
};
weavejs.api.core.IProgressIndicator.prototype.removeTask = function(taskToken) {
};
weavejs.api.core.IProgressIndicator.prototype.getNormalizedProgress = function() {
};


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
weavejs.api.core.IProgressIndicator.prototype.FLEXJS_CLASS_INFO = { names: [{ name: 'IProgressIndicator', qName: 'weavejs.api.core.IProgressIndicator'}], interfaces: [weavejs.api.core.ILinkableObject] };
