/**
 * Generated by Apache Flex Cross-Compiler from weavejs\api\core\ISessionManager.as
 * weavejs.api.core.ISessionManager
 *
 * @fileoverview
 *
 * @suppress {checkTypes}
 */

goog.provide('weavejs.api.core.ISessionManager');

goog.require('weavejs.api.core.ICallbackCollection');
goog.require('weavejs.api.core.ILinkableObject');



/**
 * @interface
 */
weavejs.api.core.ISessionManager = function() {
};
weavejs.api.core.ISessionManager.prototype.getCallbackCollection = function(linkableObject) {
};
weavejs.api.core.ISessionManager.prototype.newLinkableChild = function(linkableParent, linkableChildType, callback, useGroupedCallback) {
};
weavejs.api.core.ISessionManager.prototype.registerLinkableChild = function(linkableParent, linkableChild, callback, useGroupedCallback) {
};
weavejs.api.core.ISessionManager.prototype.newDisposableChild = function(disposableParent, disposableChildType) {
};
weavejs.api.core.ISessionManager.prototype.registerDisposableChild = function(disposableParent, disposableChild) {
};
weavejs.api.core.ISessionManager.prototype.getLinkableOwner = function(child) {
};
weavejs.api.core.ISessionManager.prototype.getLinkableDescendants = function(root, filter) {
};
weavejs.api.core.ISessionManager.prototype.assignBusyTask = function(taskToken, busyObject) {
};
weavejs.api.core.ISessionManager.prototype.unassignBusyTask = function(taskToken) {
};
weavejs.api.core.ISessionManager.prototype.linkableObjectIsBusy = function(linkableObject) {
};
weavejs.api.core.ISessionManager.prototype.setSessionState = function(linkableObject, newState, removeMissingDynamicObjects) {
};
weavejs.api.core.ISessionManager.prototype.getSessionState = function(linkableObject) {
};
weavejs.api.core.ISessionManager.prototype.computeDiff = function(oldState, newState) {
};
weavejs.api.core.ISessionManager.prototype.combineDiff = function(baseDiff, diffToAdd) {
};
weavejs.api.core.ISessionManager.prototype.copySessionState = function(source, destination) {
};
weavejs.api.core.ISessionManager.prototype.linkSessionState = function(primary, secondary) {
};
weavejs.api.core.ISessionManager.prototype.unlinkSessionState = function(first, second) {
};
weavejs.api.core.ISessionManager.prototype.disposeObject = function(object) {
};
weavejs.api.core.ISessionManager.prototype.objectWasDisposed = function(object) {
};
weavejs.api.core.ISessionManager.prototype.getPath = function(root, descendant) {
};
weavejs.api.core.ISessionManager.prototype.getObject = function(root, path) {
};


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
weavejs.api.core.ISessionManager.prototype.FLEXJS_CLASS_INFO = { names: [{ name: 'ISessionManager', qName: 'weavejs.api.core.ISessionManager'}] };
