#!/bin/bash
PROJECT=`dirname "$0"`
ROOT_PATH="$PROJECT/bin/js-debug/"
DTS_PATH="$PROJECT/definitions/"
PARAMS=""
for JS_SOURCE in $(find "$ROOT_PATH" -name "*.js"); do
	DTS_OUTPUT=$DTS_PATH${JS_SOURCE#$ROOT_PATH}
	DTS_OUTPUT=${DTS_OUTPUT%.js}.d.ts
    if ! [[ $JS_SOURCE =~ .*/library/closure/.* ]]
    then
        PARAMS="$PARAMS ${JS_SOURCE} ${DTS_OUTPUT}"
    fi
done
closure2ts --input_root $ROOT_PATH --output_root $DTS_PATH $PARAMS
