/*
    Weave (Web-based Analysis and Visualization Environment)
    Copyright (C) 2008-2011 University of Massachusetts Lowell

    This file is a part of Weave.

    Weave is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License, Version 3,
    as published by the Free Software Foundation.

    Weave is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Weave.  If not, see <http://www.gnu.org/licenses/>.
*/


package weave.utils
{
	import mx.utils.ObjectUtil;
	
	public class WordProcessingUtils
	{
		//http://www.webconfs.com/stop-words.php
		private static const stopWords:Array = [ "a",
			"able",
			"about",
			"above",
			"abroad",
			"according",
			"accordingly",
			"across",
			"actually",
			"adj",
			"after",
			"afterwards",
			"again",
			"against",
			"ago",
			"ahead",
			"ain't",
			"all",
			"allow",
			"allows",
			"almost",
			"alone",
			"along",
			"alongside",
			"already",
			"also",
			"although",
			"always",
			"am",
			"amid",
			"amidst",
			"among",
			"amongst",
			"an",
			"and",
			"another",
			"any",
			"anybody",
			"anyhow",
			"anyone",
			"anything",
			"anyway",
			"anyways",
			"anywhere",
			"apart",
			"appear",
			"appreciate",
			"appropriate",
			"are",
			"aren't",
			"around",
			"as",
			"a's",
			"aside",
			"ask",
			"asking",
			"associated",
			"at",
			"available",
			"away",
			"awfully",
			"back",
			"backward",
			"backwards",
			"be",
			"became",
			"because",
			"become",
			"becomes",
			"becoming",
			"been",
			"before",
			"beforehand",
			"begin",
			"behind",
			"being",
			"believe",
			"below",
			"beside",
			"besides",
			"best",
			"better",
			"between",
			"beyond",
			"both",
			"brief",
			"but",
			"by",
			"came",
			"can",
			"cannot",
			"cant",
			"can't",
			"caption",
			"cause",
			"causes",
			"certain",
			"certainly",
			"changes",
			"clearly",
			"c'mon",
			"co",
			"co.",
			"com",
			"come",
			"comes",
			"concerning",
			"consequently",
			"consider",
			"considering",
			"contain",
			"containing",
			"contains",
			"corresponding",
			"could",
			"couldn't",
			"course",
			"c's",
			"currently",
			"dare",
			"daren't",
			"definitely",
			"described",
			"despite",
			"did",
			"didn't",
			"different",
			"directly",
			"do",
			"does",
			"doesn't",
			"doing",
			"done",
			"don't",
			"down",
			"downwards",
			"during",
			"each",
			"edu",
			"eg",
			"eight",
			"eighty",
			"either",
			"else",
			"elsewhere",
			"end",
			"ending",
			"enough",
			"entirely",
			"especially",
			"et",
			"etc",
			"even",
			"ever",
			"evermore",
			"every",
			"everybody",
			"everyone",
			"everything",
			"everywhere",
			"ex",
			"exactly",
			"example",
			"except",
			"fairly",
			"far",
			"farther",
			"few",
			"fewer",
			"fifth",
			"first",
			"five",
			"followed",
			"following",
			"follows",
			"for",
			"forever",
			"former",
			"formerly",
			"forth",
			"forward",
			"found",
			"four",
			"from",
			"further",
			"furthermore",
			"get",
			"gets",
			"getting",
			"given",
			"gives",
			"go",
			"goes",
			"going",
			"gone",
			"got",
			"gotten",
			"greetings",
			"had",
			"hadn't",
			"half",
			"happens",
			"hardly",
			"has",
			"hasn't",
			"have",
			"haven't",
			"having",
			"he",
			"he'd",
			"he'll",
			"hello",
			"help",
			"hence",
			"her",
			"here",
			"hereafter",
			"hereby",
			"herein",
			"here's",
			"hereupon",
			"hers",
			"herself",
			"he's",
			"hi",
			"him",
			"himself",
			"his",
			"hither",
			"hopefully",
			"how",
			"howbeit",
			"however",
			"hundred",
			"i'd",
			"ie",
			"if",
			"ignored",
			"i'll",
			"i'm",
			"immediate",
			"in",
			"inasmuch",
			"inc",
			"inc.",
			"indeed",
			"indicate",
			"indicated",
			"indicates",
			"inner",
			"inside",
			"insofar",
			"instead",
			"into",
			"inward",
			"is",
			"isn't",
			"it",
			"it'd",
			"it'll",
			"its",
			"it's",
			"itself",
			"i've",
			"just",
			"k",
			"keep",
			"keeps",
			"kept",
			"know",
			"known",
			"knows",
			"last",
			"lately",
			"later",
			"latter",
			"latterly",
			"least",
			"less",
			"lest",
			"let",
			"let's",
			"like",
			"liked",
			"likely",
			"likewise",
			"little",
			"look",
			"looking",
			"looks",
			"low",
			"lower",
			"ltd",
			"made",
			"mainly",
			"make",
			"makes",
			"many",
			"may",
			"maybe",
			"mayn't",
			"me",
			"mean",
			"meantime",
			"meanwhile",
			"merely",
			"might",
			"mightn't",
			"mine",
			"minus",
			"miss",
			"more",
			"moreover",
			"most",
			"mostly",
			"mr",
			"mrs",
			"much",
			"must",
			"mustn't",
			"my",
			"myself",
			"name",
			"namely",
			"nd",
			"near",
			"nearly",
			"necessary",
			"need",
			"needn't",
			"needs",
			"neither",
			"never",
			"neverf",
			"neverless",
			"nevertheless",
			"new",
			"next",
			"nine",
			"ninety",
			"no",
			"nobody",
			"non",
			"none",
			"nonetheless",
			"noone",
			"no-one",
			"nor",
			"normally",
			"not",
			"nothing",
			"notwithstanding",
			"novel",
			"now",
			"nowhere",
			"obviously",
			"of",
			"off",
			"often",
			"oh",
			"ok",
			"okay",
			"old",
			"on",
			"once",
			"one",
			"ones",
			"one's",
			"only",
			"onto",
			"opposite",
			"or",
			"other",
			"others",
			"otherwise",
			"ought",
			"oughtn't",
			"our",
			"ours",
			"ourselves",
			"out",
			"outside",
			"over",
			"overall",
			"own",
			"particular",
			"particularly",
			"past",
			"per",
			"perhaps",
			"placed",
			"please",
			"plus",
			"possible",
			"presumably",
			"probably",
			"provided",
			"provides",
			"que",
			"quite",
			"qv",
			"rather",
			"rd",
			"re",
			"really",
			"reasonably",
			"recent",
			"recently",
			"regarding",
			"regardless",
			"regards",
			"relatively",
			"respectively",
			"right",
			"round",
			"said",
			"same",
			"saw",
			"say",
			"saying",
			"says",
			"second",
			"secondly",
			"see",
			"seeing",
			"seem",
			"seemed",
			"seeming",
			"seems",
			"seen",
			"self",
			"selves",
			"sensible",
			"sent",
			"serious",
			"seriously",
			"seven",
			"several",
			"shall",
			"shan't",
			"she",
			"she'd",
			"she'll",
			"she's",
			"should",
			"shouldn't",
			"since",
			"six",
			"so",
			"some",
			"somebody",
			"someday",
			"somehow",
			"someone",
			"something",
			"sometime",
			"sometimes",
			"somewhat",
			"somewhere",
			"soon",
			"sorry",
			"specified",
			"specify",
			"specifying",
			"still",
			"sub",
			"such",
			"sup",
			"sure",
			"take",
			"taken",
			"taking",
			"tell",
			"tends",
			"th",
			"than",
			"thank",
			"thanks",
			"thanx",
			"that",
			"that'll",
			"thats",
			"that's",
			"that've",
			"the",
			"their",
			"theirs",
			"them",
			"themselves",
			"then",
			"thence",
			"there",
			"thereafter",
			"thereby",
			"there'd",
			"therefore",
			"therein",
			"there'll",
			"there're",
			"theres",
			"there's",
			"thereupon",
			"there've",
			"these",
			"they",
			"they'd",
			"they'll",
			"they're",
			"they've",
			"thing",
			"things",
			"think",
			"third",
			"thirty",
			"this",
			"thorough",
			"thoroughly",
			"those",
			"though",
			"three",
			"through",
			"throughout",
			"thru",
			"thus",
			"till",
			"to",
			"together",
			"too",
			"took",
			"toward",
			"towards",
			"tried",
			"tries",
			"truly",
			"try",
			"trying",
			"t's",
			"twice",
			"two",
			"un",
			"under",
			"underneath",
			"undoing",
			"unfortunately",
			"unless",
			"unlike",
			"unlikely",
			"until",
			"unto",
			"up",
			"upon",
			"upwards",
			"us",
			"use",
			"used",
			"useful",
			"uses",
			"using",
			"usually",
			"v",
			"value",
			"various",
			"versus",
			"very",
			"via",
			"viz",
			"vs",
			"want",
			"wants",
			"was",
			"wasn't",
			"way",
			"we",
			"we'd",
			"welcome",
			"well",
			"we'll",
			"went",
			"were",
			"we're",
			"weren't",
			"we've",
			"what",
			"whatever",
			"what'll",
			"what's",
			"what've",
			"when",
			"whence",
			"whenever",
			"where",
			"whereafter",
			"whereas",
			"whereby",
			"wherein",
			"where's",
			"whereupon",
			"wherever",
			"whether",
			"which",
			"whichever",
			"while",
			"whilst",
			"whither",
			"who",
			"who'd",
			"whoever",
			"whole",
			"who'll",
			"whom",
			"whomever",
			"who's",
			"whose",
			"why",
			"will",
			"willing",
			"wish",
			"with",
			"within",
			"without",
			"wonder",
			"won't",
			"would",
			"wouldn't",
			"yes",
			"yet",
			"you",
			"you'd",
			"you'll",
			"your",
			"you're",
			"yours",
			"yourself",
			"yourselves",
			"you've",
			"zero" ];
		
		
		private static const infomapsStopWords:Array = ["percent"
		,"Year",
		"FIPS",
		"State",
		"States",];
		
		public static function isStopWord(word:String,includeInfomapsKeywords:Boolean = true):Boolean
		{
			for each(var w:String in stopWords)
			{
				if(w.toLowerCase() == word.toLowerCase())
					return true;
			}
			
			if(includeInfomapsKeywords)
			{
				for each(var w2:String in infomapsStopWords)
				{
					if(w2.toLowerCase() == word.toLowerCase())
					{
						return true;
					}
				}
			}
			
			return false;
		}
		
		/**
		 * @param wordData The string to parse.
		 * @param index is an object that will serve as a mapping for the words and their frequencies.
		 * @return An Array will be returned. This is an array of all the words in the parsed string.
		 */		
		public static function WordProcessingUtilsy( wordData:String, index:Object ):Array
		{
			var i:int = 0;
			var j:int;
			var k:int;
			var position:int;
			var word:String;
			var wordCollection:Array = new Array();
			var end:Boolean = false;
			var found:Boolean = false;
			
			wordCollection.length = 0;
			
			do{
				
				position = wordData.indexOf( " ", i );
				word = wordData.slice( i, position );
				
				if( position == -1 ){
					word = wordData.slice( i, wordData.length + 1 );
					i = wordData.length;
					end = true;
				}
				else
					i = position + 1;
				
				position = word.indexOf( "." );
				if( position != -1 )
					word = word.slice( 0, position );
				position = word.indexOf( "!" );
				if( position != -1 )
					word = word.slice( 0, position );
				position = word.indexOf( "?" );
				if( position != - 1 )
					word = word.slice( 0, position );
				position = word.indexOf( "," );
				if( position != - 1 )
					word = word.slice( 0, position );
				position = word.indexOf( ")" );
				if( position != -1 )
					word = word.slice( 0, position );
				position = word.indexOf( "(" );
				if( position != -1 )
					word = word.slice( position + 1 );
				position = word.indexOf( "\"" );
				if( position != -1 ){
					if( position > 0 )
						word = word.slice( 0, position );
					else if( position == 0 )
						word = word.slice( position + 1 );
				}
				position = word.indexOf( "\"" );
				if( position != -1 ){
					if( position > 0 )
						word = word.slice( 0, position );
					else if( position == 0 )
						word = word.slice( position + 1 );
				}		
								
				for( k = 0; k < stopWords.length; k++ ){
					if( word == stopWords[k] )
						found = true;
					if( found == true )
						break;
				}
				
				if( found != true ){
					
				for( j = 0; j < wordCollection.length; j++ ) {
					
					if( wordCollection[j] == word )
						break;
					if( ( j + 1 ) == wordCollection.length ){
						wordCollection[j+1] = word;
						index[word] = 0;
					}
				}
				
				if( wordCollection.length == 0 ){
					wordCollection[0] = word;
					index[word] = 0;
				}
					
				if( index[word] == 0 )
					index[word] = 1;
				else
					index[word] = index[word] + 1;
			
				}
				
				found = false;
				
			}while( end != true );
			
			return wordCollection;
		
		}
	}
}