/*
Weave (Web-based Analysis and Visualization Environment)
Copyright (C) 2008-2011 University of Massachusetts Lowell

This file is a part of Weave.

Weave is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License, Version 3,
as published by the Free Software Foundation.

Weave is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Weave.  If not, see <http://www.gnu.org/licenses/>.
*/

package
{
	/**
	 * References all classes in the library.
	 * For use with mobile app.
	 * 
	 * @author adufilie
	 */
	public class AllClasses
	{
		// WeaveAPI
		_InitializeWeaveCore;
		_InitializeWeaveData;
		
		import com.hurlant.crypto.hash.IHash;
		import com.modestmaps.mapproviders.AbstractMapProvider;
		import com.modestmaps.mapproviders.IMapProvider;
		import com.modestmaps.mapproviders.yahoo.YahooOverlayMapProvider;
		
		debugId as Function;
		debugLookup as Function;
		debugTrace as Function;
		lang as Function;
		
		import nochump.util.zip.CRC32;
		import nochump.util.zip.Deflater;
		import nochump.util.zip.Inflater;
		import nochump.util.zip.ZipConstants;
		import nochump.util.zip.ZipEntry;
		import nochump.util.zip.ZipError;
		import nochump.util.zip.ZipFile;
		import nochump.util.zip.ZipOutput;
		
		import org.igniterealtime.xiff.auth.SASLAuth;
		import org.igniterealtime.xiff.collections.ArrayCollection;
		import org.igniterealtime.xiff.core.AbstractJID;
		import org.igniterealtime.xiff.core.UnescapedJID;
		import org.igniterealtime.xiff.data.Extension;
		import org.igniterealtime.xiff.data.ExtensionClassRegistry;
		import org.igniterealtime.xiff.data.ExtensionContainer;
		import org.igniterealtime.xiff.data.IExtendable;
		import org.igniterealtime.xiff.data.IExtension;
		import org.igniterealtime.xiff.data.INodeProxy;
		import org.igniterealtime.xiff.data.ISerializable;
		import org.igniterealtime.xiff.data.XMLStanza;
		import org.igniterealtime.xiff.data.muc.MUCAdminExtension;
		import org.igniterealtime.xiff.data.muc.MUCBaseExtension;
		import org.igniterealtime.xiff.events.ChangePasswordSuccessEvent;
		import org.openscales.proj4as.proj.ProjParams;
		
		import weave.api.WeaveAPI;
		import weave.api.WeaveArchive;
		import weave.api.copySessionState;
		import weave.api.core.ICallbackCollection;
		import weave.api.core.IChildListCallbackInterface;
		import weave.api.core.IDisposableObject;
		import weave.api.core.IErrorManager;
		import weave.api.core.IExternalSessionStateInterface;
		import weave.api.core.ILinkableCompositeObject;
		import weave.api.core.ILinkableContainer;
		import weave.api.core.ILinkableDisplayObject;
		import weave.api.core.ILinkableDynamicObject;
		import weave.api.core.ILinkableHashMap;
		import weave.api.core.ILinkableObject;
		import weave.api.core.ILinkableObjectWithBusyStatus;
		import weave.api.core.ILinkableVariable;
		import weave.api.core.ILocaleManager;
		import weave.api.core.IProgressIndicator;
		import weave.api.core.ISessionManager;
		import weave.api.core.IStageUtils;
		import weave.api.data.AttributeColumnMetadata;
		import weave.api.data.DataTypes;
		import weave.api.data.IAttributeColumn;
		import weave.api.data.IAttributeColumnCache;
		import weave.api.data.IAttributeHierarchy;
		import weave.api.data.IBinClassifier;
		import weave.api.data.IBinningDefinition;
		import weave.api.data.ICSVExportable;
		import weave.api.data.ICSVParser;
		import weave.api.data.IColumnReference;
		import weave.api.data.IColumnStatistics;
		import weave.api.data.IColumnWrapper;
		import weave.api.data.IDataRowSource;
		import weave.api.data.IDataSource;
		import weave.api.data.IDynamicKeyFilter;
		import weave.api.data.IFilteredKeySet;
		import weave.api.data.IKeyFilter;
		import weave.api.data.IKeySet;
		import weave.api.data.IPrimitiveColumn;
		import weave.api.data.IProjectionManager;
		import weave.api.data.IProjector;
		import weave.api.data.IQualifiedKey;
		import weave.api.data.IQualifiedKeyManager;
		import weave.api.data.ISimpleGeometry;
		import weave.api.data.IStatisticsCache;
		import weave.api.detectLinkableObjectChange;
		import weave.api.disposeObjects;
		import weave.api.getCallbackCollection;
		import weave.api.getLinkableDescendants;
		import weave.api.getLinkableOwner;
		import weave.api.getLinkableRoot;
		import weave.api.getSessionState;
		import weave.api.graphs.IGraphAlgorithm;
		import weave.api.graphs.IGraphNode;
		import weave.api.juggleGroupedCallback;
		import weave.api.juggleImmediateCallback;
		import weave.api.linkBindableProperty;
		import weave.api.linkSessionState;
		import weave.api.linkableObjectIsBusy;
		import weave.api.newDisposableChild;
		import weave.api.newLinkableChild;
		import weave.api.objectWasDisposed;
		import weave.api.primitives.IBounds2D;
		import weave.api.primitives.IMatrix;
		import weave.api.radviz.ILayoutAlgorithm;
		import weave.api.registerDisposableChild;
		import weave.api.registerLinkableChild;
		import weave.api.reportError;
		import weave.api.services.IAsyncService;
		import weave.api.services.IURLRequestToken;
		import weave.api.services.IURLRequestUtils;
		import weave.api.services.IWMSService;
		import weave.api.services.IWeaveDataService;
		import weave.api.services.IWeaveGeometryTileService;
		import weave.api.setSessionState;
		import weave.api.ui.ICollabCursorManager;
		import weave.api.ui.IFillStyle;
		import weave.api.ui.ILineStyle;
		import weave.api.ui.ILinkableObjectEditor;
		import weave.api.ui.IPlotTask;
		import weave.api.ui.IPlotter;
		import weave.api.ui.IPlotterWithGeometries;
		import weave.api.ui.IProbeDisplay;
		import weave.api.ui.ISpatialIndex;
		import weave.api.ui.ITextPlotter;
		import weave.api.ui.IVisTool;
		import weave.api.ui.IVisToolWithSelectableAttributes;
		import weave.api.unlinkBindableProperty;
		import weave.api.unlinkSessionState;
		import weave.compiler.CompiledConstant;
		import weave.compiler.CompiledFunctionCall;
		import weave.compiler.Compiler;
		import weave.compiler.GlobalLib;
		import weave.compiler.ICompiledObject;
		import weave.compiler.ProxyObject;
		import weave.compiler.StandardLib;
		import weave.core.CallbackCollection;
		import weave.core.CallbackJuggler;
		import weave.core.ChildListCallbackInterface;
		import weave.core.ClassUtils;
		import weave.core.DynamicState;
		import weave.core.ErrorManager;
		import weave.core.ExternalSessionStateInterface;
		import weave.core.GlobalObjectReference;
		import weave.core.LibraryUtils;
		import weave.core.LinkableBoolean;
		import weave.core.LinkableDisplayObject;
		import weave.core.LinkableDynamicObject;
		import weave.core.LinkableFunction;
		import weave.core.LinkableHashMap;
		import weave.core.LinkableNumber;
		import weave.core.LinkableProxyObject;
		import weave.core.LinkableString;
		import weave.core.LinkableVariable;
		import weave.core.LinkableWrapper;
		import weave.core.LinkableXML;
		import weave.core.LocaleManager;
		import weave.core.ProgressIndicator;
		import weave.core.SessionManager;
		import weave.core.SessionStateLog;
		import weave.core.StageUtils;
		import weave.core.UIUtils;
		import weave.core.UntypedLinkableVariable;
		import weave.core.WeaveXMLDecoder;
		import weave.core.WeaveXMLEncoder;
		import weave.data.AttributeColumns.DynamicColumn;
		import weave.data.BinningDefinitions.AbstractBinningDefinition;
		import weave.data.BinningDefinitions.SimpleBinningDefinition;
		import weave.graphs.AbstractGraphAlgorithm;
		import weave.graphs.KamadaKawaiLayout;
		import weave.radviz.AbstractLayoutAlgorithm;
		import weave.radviz.RandomLayoutAlgorithm;
		import weave.services.wms.AbstractWMS;
		import weave.utils.AsyncSort;
		import weave.utils.DebugTimer;
		import weave.utils.DebugUtils;
		import weave.utils.Dictionary2D;
		import weave.utils.OrderedHashMap;
		import weave.utils.WeakReference;
		import weave.utils.debug_trace;
		org.openscales.proj4as.proj.IProjection;
		import org.openscales.proj4as.proj.AbstractProjProjection;
		import weave.data.KeySets.NumericDataFilter;
		import weave.radviz.MatrixEntry;
		import org.igniterealtime.xiff.data.xhtml.XHTMLExtension;
		import com.as3xls.cdf.CDFReader;
		import weave.data.AttributeColumns.AbstractAttributeColumn;
		import weave.data.AttributeColumns.StreamedGeometryColumn;
		import org.vanrijkom.dbf.DbfHeader;
		import weave.primitives.ColorRamp;
		import org.igniterealtime.xiff.data.XMPPStanza;
		import org.igniterealtime.xiff.data.Message;
		import weave.services.wms.WMSTileIndex;
		import org.vanrijkom.shp.ShpHeader;
		import weave.services.jquery.JQueryCaller_JQCaller;
		import org.openscales.proj4as.proj.ProjOmerc;
		import com.modestmaps.geo.IProjection;
		IProjection;
		import com.modestmaps.mapproviders.OpenStreetMapProvider;
		import weave.utils.EquationColumnLib;
		import org.igniterealtime.xiff.data.muc.MUCUserExtension;
		import org.igniterealtime.xiff.collections.events.CollectionEvent;
		import weave.radviz.BruteForceLayoutAlgorithm;
		import weave.services.beans.KMeansClusteringResult;
		import weave.services.DelayedAsyncResponder;
		import com.as3xls.biff.BIFFReader;
		import org.openscales.proj4as.ProjPoint;
		import weave.primitives.GeneralizedGeometry;
		import org.openscales.proj4as.proj.ProjAea;
		import org.igniterealtime.xiff.events.PresenceEvent;
		import weave.primitives.Geometry;
		import org.igniterealtime.xiff.data.id.IIDGenerator;
		import weave.services.beans.DensityBasedClusteringResult;
		import weave.data.BinClassifiers.BinClassifierCollection;
		import weave.data.BinningDefinitions.ExplicitBinningDefinition;
		import weave.data.AttributeColumns.ExtendedDynamicColumn;
		import weave.data.AttributeColumns.ColorColumn;
		import weave.services.DelayedAsyncInvocation;
		import weave.primitives.ZoomBounds;
		import org.igniterealtime.xiff.data.im.Contact;
		import org.igniterealtime.xiff.data.im.RosterItemVO;
		import weave.primitives.KDNode;
		import org.igniterealtime.xiff.util.SHA1;
		import weave.graphs.LargeGraphLayout;
		import weave.data.KeySets.KeySetUnion;
		import weave.data.AttributeColumns.ProxyColumn;
		import org.igniterealtime.xiff.data.im.RosterExtension;
		import weave.data.BinningDefinitions.DynamicBinningDefinition;
		import weave.data.KeySets.SortedKeySet;
		import org.igniterealtime.xiff.events.ConnectionSuccessEvent;
		import weave.services.collaboration.CollaborationService;
		import org.openscales.proj4as.proj.ProjEqdc;
		import weave.data.BinClassifiers.SingleValueClassifier;
		import org.vanrijkom.shp.ShpError;
		import weave.utils.ImageLoaderUtils;
		import org.igniterealtime.xiff.events.PropertyChangeEvent;
		import weave.utils.NumberUtils;
		import weave.primitives.SimpleGeometry;
		import org.vanrijkom.shp.ShpObject;
		import org.vanrijkom.shp.ShpPoint;
		import weave.data.DataSources.AbstractDataSource;
		import weave.data.DataSources.DBFDataSource;
		import weave.data.BinClassifiers.NumberClassifier;
		import org.openscales.proj4as.proj.ProjNzmg;
		import com.as3xls.xls.Formatter;
		import weave.graphs.DynamicGraphAlgorithm;
		import weave.data.KeySets.DynamicKeyFilter;
		import weave.data.BinningDefinitions.CategoryBinningDefinition;
		import org.vanrijkom.far.FarEvent;
		import org.vanrijkom.shp.ShpTools;
		import weave.services.Servlet;
		import weave.services.WFSServlet;
		import org.vanrijkom.shp.ShpType;
		import org.igniterealtime.xiff.events.IncomingDataEvent;
		import weave.services.WeaveRServlet;
		import weave.data.AttributeColumns.ReprojectedGeometryColumn;
		import org.openscales.proj4as.proj.ProjLaea;
		import weave.utils.HierarchyUtils;
		import weave.data.BinningDefinitions.CustomSplitBinningDefinition;
		import com.modestmaps.mapproviders.microsoft.MicrosoftProvider;
		import com.as3xls.biff.Record;
		import org.igniterealtime.xiff.events.RoomEvent;
		import org.igniterealtime.xiff.data.forms.FormExtension;
		import weave.graphs.GraphNode;
		import org.igniterealtime.xiff.events.OutgoingDataEvent;
		import weave.primitives.BLGTree;
		import weave.primitives.LinkableNumberFormatter;
		import org.igniterealtime.xiff.data.muc.MUCStatus;
		import weave.primitives.LooseAxisDescription;
		import com.as3xls.xls.formula.Tokens;
		import org.igniterealtime.xiff.exception.SerializationException;
		import org.vanrijkom.dbf.DbfFilter;
		import weave.data.AttributeColumns.WordCountColumn;
		import com.as3xls.xls.ExcelFile;
		import weave.data.BinClassifiers.StringClassifier;
		import weave.primitives.Bounds2D;
		import org.igniterealtime.xiff.data.id.IncrementalGenerator;
		import org.igniterealtime.xiff.auth.Plain;
		import org.igniterealtime.xiff.events.MessageEvent;
		import com.modestmaps.geo.AbstractProjection;
		import weave.services.collaboration.CollaborationEvent;
		import weave.utils.WordProcessingUtils;
		import weave.primitives.VertexChainLink;
		import weave.services.beans.LinearRegressionResult;
		import org.igniterealtime.xiff.core.EscapedJID;
		import weave.data.ProjectionManager_ProjDatabase;
		import com.as3xls.cdf.Directory;
		import weave.data.AttributeColumns.AggregatedColumn;
		import weave.services.jquery.JQueryCaller_JQ;
		import weave.services.beans.GeometryStreamMetadata;
		import weave.services.AsyncInvocationQueue;
		import weave.services.WebServiceWrapper;
		import weave.services.wms.StamenProvider;
		import org.igniterealtime.xiff.conference.RoomOccupant;
		import org.openscales.proj4as.ProjProjection;
		import com.modestmaps.mapproviders.yahoo.YahooRoadMapProvider;
		import org.openscales.proj4as.proj.ProjEqui;
		import com.modestmaps.core.Coordinate;
		import weave.data.AttributeColumns.SortedIndexColumn;
		import org.openscales.proj4as.Datum;
		import weave.primitives.WeaveMatrix;
		import weave.data.AttributeColumns.StringColumn;
		import org.igniterealtime.xiff.data.forms.FormField;
		import weave.data.DataSources.MultiDataSource;
		import org.igniterealtime.xiff.collections.events.CollectionEventKind;
		import org.igniterealtime.xiff.data.auth.AuthExtension;
		import weave.data.AttributeColumns.EquationColumn;
		import weave.data.DataSources.XLSDataSource;
		import org.openscales.proj4as.proj.ProjSinu;
		import weave.data.AttributeColumns.KeyColumn;
		import org.openscales.proj4as.proj.ProjAeqd;
		import weave.data.ProjectionManager;
		import weave.primitives.Range;
		import org.openscales.proj4as.proj.ProjMill;
		import weave.utils.RadVizUtils;
		import org.openscales.proj4as.proj.ProjTmerc;
		import weave.data.DataSources.CSVDataSource;
		import org.openscales.proj4as.proj.ProjMoll;
		import com.modestmaps.geo.Location;
		import org.igniterealtime.xiff.auth.Anonymous;
		import weave.data.AttributeColumns.AlwaysDefinedColumn;
		import weave.services.beans.AttributeColumnDataWithKeys;
		import weave.services.beans.RResult;
		import org.igniterealtime.xiff.data.muc.MUCExtension;
		import org.igniterealtime.xiff.events.IQEvent;
		import org.openscales.proj4as.proj.ProjLonglat;
		import weave.services.wms.OpenMapQuestAerialProvider;
		import weave.data.ColumnReferences.AbstractColumnReference;
		import org.igniterealtime.xiff.data.bind.BindExtension;
		import org.igniterealtime.xiff.data.muc.MUCItem;
		import weave.data.DataSources.WeaveDataSource;
		import weave.utils.ImageLoaderUtilsEvent;
		import org.igniterealtime.xiff.data.muc.MUCOwnerExtension;
		import org.igniterealtime.xiff.conference.Room;
		import weave.data.AttributeColumns.NormalizedColumn;
		import org.openscales.proj4as.proj.ProjGauss;
		import org.openscales.proj4as.proj.ProjSterea;
		import weave.data.AttributeColumns.GeometryColumn;
		import org.vanrijkom.dbf.DbfRecord;
		import weave.utils.ZoomUtils;
		import org.igniterealtime.xiff.core.XMPPConnection;
		import org.igniterealtime.xiff.data.muc.MUC;
		import weave.radviz.GreedyLayoutAlgorithm;
		import weave.data.AttributeColumns.ReferencedColumn;
		import org.igniterealtime.xiff.data.IQ;
		import org.igniterealtime.xiff.auth.DigestMD5;
		import weave.data.KeySets.FilteredKeySet;
		import weave.data.KeySets.KeyFilter;
		import org.openscales.proj4as.ProjConstants;
		import weave.services.beans.DataServiceMetadata;
		import weave.data.QKeyManager;
		import com.as3xls.xls.Type;
		import weave.services.wms.OnEarthProvider;
		import weave.services.wms.OpenMapQuestProvider;
		import weave.data.AttributeColumns.SecondaryKeyNumColumn;
		import weave.data.AttributeColumns.NumberColumn;
		import weave.services.beans.DataTableMetadata;
		import com.hurlant.util.Base64;
		import weave.primitives.Bounds2DIndex;
		import org.vanrijkom.shp.ShpPolygon;
		import com.modestmaps.geo.Transformation;
		import org.igniterealtime.xiff.auth.External;
		import com.as3xls.biff.BIFFVersion;
		import org.igniterealtime.xiff.events.RegistrationFieldsEvent;
		import org.vanrijkom.shp.ShpPolyline;
		import weave.services.URLRequestUtils;
		import com.as3xls.xls.style.XFormat;
		import org.igniterealtime.xiff.data.register.RegisterExtension;
		import weave.data.AttributeColumnCache;
		import com.modestmaps.mapproviders.yahoo.YahooHybridMapProvider;
		import org.vanrijkom.shp.ShpPointZ;
		import weave.data.AttributeColumns.ImageColumn__missingImageClass;
		import weave.services.LocalAsyncService;
		import weave.radviz.IncrementalLayoutAlgorithm;
		import weave.graphs.GridForceDirectedLayout;
		import weave.services.wms.WMSProviders;
		import org.openscales.proj4as.proj.ProjVandg;
		import weave.data.StatisticsCache;
		import org.openscales.proj4as.proj.ProjGstmerc;
		import com.as3xls.xls.Sheet;
		import weave.services.wms.WMSTile;
		import com.hurlant.crypto.hash.MD5;
		import weave.services.WeaveDataServlet;
		import org.igniterealtime.xiff.data.session.SessionExtension;
		import weave.data.BinningDefinitions.EqualIntervalBinningDefinition;
		import org.igniterealtime.xiff.events.DisconnectionEvent;
		import org.openscales.proj4as.Proj4as;
		import weave.utils.GeometryStreamDecoder;
		import weave.radviz.NearestNeighborLayoutAlgorithm;
		import com.modestmaps.util.BinaryUtil;
		import com.as3xls.xls.Cell;
		import weave.data.KeySets.KeySet;
		import weave.utils.BLGTreeUtils;
		import weave.primitives.ImageFactory;
		import weave.utils.ComputationalGeometryUtils;
		import weave.data.DataSources.WFSDataSource;
		import weave.data.ColumnReferences.UntypedColumnReference;
		import weave.services.AsyncServiceQueue;
		import weave.primitives.BLGNode;
		import weave.Reports.WeaveReport;
		import org.openscales.proj4as.proj.ProjMerc;
		import weave.services.AMF3Servlet;
		import weave.graphs.ForceDirectedLayout;
		import weave.data.ColumnReferences.HierarchyColumnReference;
		import weave.utils.EventUtils;
		import weave.services.wms.ModestMapsWMS;
		import org.vanrijkom.dbf.DbfField;
		import weave.data.AttributeColumns.StringLookup;
		import org.openscales.proj4as.proj.ProjEqc;
		import weave.utils.ShpFileReader;
		import org.openscales.proj4as.proj.ProjOrtho;
		import weave.utils.ObjectPool;
		import org.igniterealtime.xiff.events.XIFFErrorEvent;
		import com.hurlant.util.Hex;
		import org.vanrijkom.far.FarStream;
		import com.modestmaps.mapproviders.BlueMarbleMapProvider;
		import weave.graphs.GraphEdge;
		import weave.primitives.ColorRamp_ColorRampPresetsXML;
		import weave.data.AttributeColumns.SortedColumn;
		import weave.utils.VectorUtils;
		import org.vanrijkom.dbf.DbfTools;
		import weave.data.AttributeColumns.BinnedColumn;
		import com.as3xls.xls.formula.Formula;
		import weave.services.beans.HierarchicalClusteringResult;
		import weave.data.AttributeColumns.FilteredColumn;
		import org.openscales.proj4as.proj.ProjStere;
		import org.vanrijkom.shp.ShpRecord;
		import org.igniterealtime.xiff.events.LoginEvent;
		import com.modestmaps.mapproviders.yahoo.YahooAerialMapProvider;
		import weave.utils.PopUpUtils;
		import org.igniterealtime.xiff.data.im.RosterItem;
		import org.openscales.proj4as.proj.ProjSoMerc;
		import weave.primitives.KDTree;
		import org.vanrijkom.far.FarItem;
		import com.as3xls.biff.BIFFWriter;
		import org.igniterealtime.xiff.data.ping.PingExtension;
		import weave.services.WeavePDBServlet;
		import weave.data.CSVParser;
		import weave.services.jquery.JQueryCaller;
		import weave.utils.CSSUtils;
		import com.modestmaps.geo.MercatorProjection;
		import weave.utils.ColumnUtils;
		import org.igniterealtime.xiff.data.Presence;
		import org.openscales.proj4as.proj.ProjLcc;
		import weave.data.AttributeColumns.ImageColumn;
		import org.vanrijkom.dbf.DbfError;
		import org.igniterealtime.xiff.events.RegistrationSuccessEvent;
		import com.as3xls.xls.formula.Functions;
		import weave.data.KeySets.StringDataFilter;
		import weave.data.AttributeColumns.CSVColumn;
		import weave.data.KeySets.DynamicKeySet;
		import weave.data.BinningDefinitions.QuantileBinningDefinition;
		import weave.primitives.AttributeHierarchy;
		import weave.data.AttributeColumns.StringLookupColumn;
		import weave.primitives.LinkableBounds2D;
		import org.openscales.proj4as.proj.ProjUtm;
		import weave.services.wms.OnEarthProvider__tileRequestClass;
		import weave.data.BinningDefinitions.StandardDeviationBinningDefinition;
		// WeaveUISpark
		import weave.visualization.plotters.AbstractPlotter;
		import weave.visualization.plotters.AbstractGlyphPlotter;
		import weave.visualization.plotters.SimpleGlyphPlotter;
		import _InitializeWeaveUISpark;
		import weave.utils.VisToolGroup;
		import weave.visualization.plotters.AnchorPlotter;
		import weave.visualization.plotters.CircleGlyphPlotter;
		import weave.visualization.plotters.CompoundBarChartPlotter;
		import weave.ui.BusyIndicator;
		import weave.ui.CustomContextMenuManager;
		import weave.visualization.layers.filters.LinkableDropShadowFilter;
		import weave.visualization.layers.InteractionController;
		import weave.visualization.plotters.MeterPlotter;
		import weave.visualization.plotters.GaugePlotter;
		import weave.utils.RadialAxis;
		import weave.visualization.plotters.BoundsPlotter;
		import weave.visualization.plotters.LinePlotter;
		import weave.visualization.plotters.RegressionLinePlotter;
		import weave.visualization.plotters.WMSPlotter;
		import weave.visualization.plotters.TextGlyphPlotter;
		import weave.utils.LinkableTextFormat;
		import weave.visualization.plotters.PieChartHistogramPlotter;
		import weave.visualization.layers.Visualization;
		import weave.visualization.plotters.ImageGlyphPlotter;
		import weave.visualization.plotters.GridLinePlotter;
		import weave.utils.TickMarkUtils;
		import weave.visualization.layers.PlotTask;
		import weave.visualization.plotters.SimpleAxisPlotter;
		import weave.visualization.layers.LayerSettings;
		import weave.utils.ResultUtils;
		import weave.visualization.plotters.styles.SolidFillStyle;
		import weave.visualization.plotters.styles.ExtendedFillStyle;
		import weave.visualization.plotters.AxisLabelPlotter;
		import weave.utils.EditorManager;
		import weave.utils.BitmapText;
		import weave.visualization.layers.LinkableEventListener;
		import weave.visualization.plotters.CirclePlotter;
		import weave.visualization.plotters.ParallelCoordinatesPlotter;
		import weave.utils.PlotUtils;
		import weave.Weave;
		import weave.visualization.plotters.CompoundRadVizPlotter;
		import weave.visualization.plotters.RamachandranBackgroundPlotter;
		import ru.etcs.utils.FontLoader;
		import weave.visualization.layers.InteractiveVisualization;
		import weave.visualization.plotters.SingleImagePlotter;
		import weave.utils.BitmapUtils;
		import weave.visualization.layers.filters.LinkableGlowFilter;
		import weave.visualization.plotters.ColorBinLegendPlotter;
		import weave.visualization.plotters.RadVizPlotter;
		import weave.visualization.plotters.Histogram2DPlotter;
		import weave.visualization.plotters.RectanglePlotter;
		import weave.visualization.layers.SimpleInteractiveVisualization;
		import weave.visualization.plotters.SizeBinLegendPlotter;
		import weave.visualization.plotters.styles.DynamicFillStyle;
		import weave.utils.DrawUtils;
		import weave.visualization.plotters.styles.DynamicLineStyle;
		import weave.visualization.plotters.styles.SolidLineStyle;
		import weave.visualization.plotters.ProbeLinePlotter;
		import weave.utils.SpatialIndex;
		import weave.visualization.plotters.GeometryPlotter;
		import weave.visualization.plotters.GraphPlotter;
		import weave.visualization.plotters.styles.ExtendedLineStyle;
		import weave.visualization.plotters.ThermometerPlotter;
		import weave.visualization.plotters.PieChartPlotter;
		import weave.visualization.plotters.AxisPlotter;
		import weave.visualization.plotters.HistogramPlotter;
		import weave.utils.PlotterUtils;
		import weave.visualization.plotters.WedgePlotter;
		import weave.visualization.plotters.AnchorPoint;
		import weave.visualization.layers.PlotManager;
		import weave.visualization.plotters.GraphLabelPlotter;
		import weave.WeaveProperties;
		import weave.visualization.plotters.StickFigureGlyphPlotter;
		import weave.utils.CustomCursorManager;
		import weave.utils.ProbeTextUtils;
		import weave.ui.PenTool;
		import weave.visualization.plotters.ScatterPlotPlotter;
		import weave.visualization.plotters.GeometryLabelPlotter;
		import weave.utils.LegendUtils;
		import weave.visualization.plotters.BarChartLegendPlotter;
		import weave.visualization.plotters.WeaveWordlePlotter;
		
		//-----------------------------------------------------------
		
		// WeaveAPI
		ILinkableObject;
		ICallbackCollection;
		IKeyFilter;
		IKeySet;
		IAttributeColumn;
		ZipError;
		juggleGroupedCallback as Function;
		IColumnWrapper;
		ICollabCursorManager;
		DataTypes;
		newLinkableChild as Function;
		unlinkSessionState as Function;
		ILinkableCompositeObject;
		getLinkableDescendants as Function;
		Deflater;
		IColumnReference;
		IChildListCallbackInterface;
		IBinningDefinition;
		getCallbackCollection as Function;
		ICSVParser;
		IWMSService;
		IBounds2D;
		getLinkableOwner as Function;
		OrderedHashMap;
		IMatrix;
		IQualifiedKey;
		IAsyncService;
		reportError as Function;
		CRC32;
		ILinkableHashMap;
		IQualifiedKeyManager;
		newDisposableChild as Function;
		ILineStyle;
		copySessionState as Function;
		IErrorManager;
		WeaveArchive;
		ILinkableContainer;
		ICSVExportable;
		IProjectionManager;
		IStatisticsCache;
		objectWasDisposed as Function;
		IProgressIndicator;
		ILocaleManager;
		detectLinkableObjectChange as Function;
		IVisTool;
		IPrimitiveColumn;
		ILayoutAlgorithm;
		linkBindableProperty as Function;
		disposeObjects as Function;
		ZipOutput;
		IWeaveDataService;
		ISpatialIndex;
		getSessionState as Function;
		ZipFile;
		ILinkableDynamicObject;
		IDynamicKeyFilter;
		IProjector;
		IURLRequestToken;
		ISimpleGeometry;
		IAttributeColumnCache;
		registerDisposableChild as Function;
		IAttributeHierarchy;
		IURLRequestUtils;
		IGraphAlgorithm;
		IPlotter;
		IPlotterWithGeometries;
		juggleImmediateCallback as Function;
		AttributeColumnMetadata;
		WeaveAPI;
		lang as Function;
		IProbeDisplay;
		setSessionState as Function;
		linkableObjectIsBusy as Function;
		ILinkableObjectWithBusyStatus;
		Inflater;
		IStageUtils;
		ITextPlotter;
		IExternalSessionStateInterface;
		ZipEntry;
		IBinClassifier;
		IDisposableObject;
		ISessionManager;
		IColumnStatistics;
		registerLinkableChild as Function;
		linkSessionState as Function;
		IFilteredKeySet;
		getLinkableRoot as Function;
		IWeaveGeometryTileService;
		IDataSource;
		IDataRowSource;
		unlinkBindableProperty as Function;
		IGraphNode;
		ILinkableDisplayObject;
		IPlotTask;
		IFillStyle;
		ILinkableObjectEditor;
		IVisToolWithSelectableAttributes;
		ILinkableVariable;
		// WeaveCore
		ClassUtils;
		debugId as Function;
		CallbackCollection;
		LinkableVariable;
		ICompiledObject;
		LocaleManager;
		SessionStateLog;
		LibraryUtils;
		_InitializeWeaveCore;
		LinkableWrapper;
		GlobalLib;
		debugLookup as Function;
		DebugTimer;
		LinkableDisplayObject;
		StandardLib;
		LinkableXML;
		LinkableBoolean;
		AsyncSort;
		debugTrace as Function;
		DebugUtils;
		CallbackJuggler;
		CompiledConstant;
		Dictionary2D;
		WeaveXMLEncoder;
		StageUtils;
		GlobalObjectReference;
		ProxyObject;
		DynamicState;
		LinkableString;
		LinkableHashMap;
		LinkableProxyObject;
		LinkableFunction;
		ChildListCallbackInterface;
		UntypedLinkableVariable;
		ProgressIndicator;
		UIUtils;
		SessionManager;
		LinkableDynamicObject;
		WeakReference;
		LinkableNumber;
		CompiledFunctionCall;
		ExternalSessionStateInterface;
		ErrorManager;
		Compiler;
		WeaveXMLDecoder;
		// WeaveData
		ChangePasswordSuccessEvent;
		AbstractBinningDefinition;
		SimpleBinningDefinition;
		_InitializeWeaveData;
		ExtensionClassRegistry;
		AbstractGraphAlgorithm;
		KamadaKawaiLayout;
		debug_trace as Function;
		DynamicColumn;
		ArrayCollection;
		IExtension;
		INodeProxy;
		IExtendable;
		ExtensionContainer;
		XMLStanza;
		Extension;
		ISerializable;
		MUCBaseExtension;
		MUCAdminExtension;
		AbstractLayoutAlgorithm;
		RandomLayoutAlgorithm;
		SASLAuth;
		AbstractWMS;
		IMapProvider;
		AbstractMapProvider;
		YahooOverlayMapProvider;
		IHash;
		AbstractJID;
		UnescapedJID;
		ProjParams;
		AbstractProjProjection;
		NumericDataFilter;
		MatrixEntry;
		XHTMLExtension;
		CDFReader;
		AbstractAttributeColumn;
		StreamedGeometryColumn;
		DbfHeader;
		ColorRamp;
		XMPPStanza;
		Message;
		WMSTileIndex;
		ShpHeader;
		JQueryCaller_JQCaller;
		ProjOmerc;
		OpenStreetMapProvider;
		EquationColumnLib;
		MUCUserExtension;
		CollectionEvent;
		BruteForceLayoutAlgorithm;
		KMeansClusteringResult;
		DelayedAsyncResponder;
		BIFFReader;
		ProjPoint;
		GeneralizedGeometry;
		ProjAea;
		PresenceEvent;
		Geometry;
		IIDGenerator;
		DensityBasedClusteringResult;
		BinClassifierCollection;
		ExplicitBinningDefinition;
		ExtendedDynamicColumn;
		ColorColumn;
		DelayedAsyncInvocation;
		ZoomBounds;
		Contact;
		RosterItemVO;
		KDNode;
		SHA1;
		LargeGraphLayout;
		KeySetUnion;
		ProxyColumn;
		RosterExtension;
		DynamicBinningDefinition;
		SortedKeySet;
		ConnectionSuccessEvent;
		CollaborationService;
		ProjEqdc;
		SingleValueClassifier;
		ShpError;
		ImageLoaderUtils;
		PropertyChangeEvent;
		NumberUtils;
		SimpleGeometry;
		ShpObject;
		ShpPoint;
		AbstractDataSource;
		DBFDataSource;
		NumberClassifier;
		ProjNzmg;
		Formatter;
		DynamicGraphAlgorithm;
		DynamicKeyFilter;
		CategoryBinningDefinition;
		FarEvent;
		ShpTools;
		Servlet;
		WFSServlet;
		ShpType;
		IncomingDataEvent;
		WeaveRServlet;
		ReprojectedGeometryColumn;
		ProjLaea;
		HierarchyUtils;
		CustomSplitBinningDefinition;
		MicrosoftProvider;
		Record;
		RoomEvent;
		FormExtension;
		GraphNode;
		OutgoingDataEvent;
		BLGTree;
		LinkableNumberFormatter;
		MUCStatus;
		LooseAxisDescription;
		Tokens;
		SerializationException;
		DbfFilter;
		WordCountColumn;
		ExcelFile;
		StringClassifier;
		Bounds2D;
		IncrementalGenerator;
		Plain;
		MessageEvent;
		AbstractProjection;
		CollaborationEvent;
		WordProcessingUtils;
		VertexChainLink;
		LinearRegressionResult;
		EscapedJID;
		ProjectionManager_ProjDatabase;
		Directory;
		AggregatedColumn;
		JQueryCaller_JQ;
		GeometryStreamMetadata;
		AsyncInvocationQueue;
		WebServiceWrapper;
		StamenProvider;
		RoomOccupant;
		ProjProjection;
		YahooRoadMapProvider;
		ProjEqui;
		Coordinate;
		SortedIndexColumn;
		Datum;
		WeaveMatrix;
		StringColumn;
		FormField;
		MultiDataSource;
		CollectionEventKind;
		AuthExtension;
		EquationColumn;
		XLSDataSource;
		ProjSinu;
		KeyColumn;
		ProjAeqd;
		ProjectionManager;
		Range;
		ProjMill;
		RadVizUtils;
		ProjTmerc;
		CSVDataSource;
		ProjMoll;
		Location;
		Anonymous;
		AlwaysDefinedColumn;
		AttributeColumnDataWithKeys;
		RResult;
		MUCExtension;
		IQEvent;
		ProjLonglat;
		OpenMapQuestAerialProvider;
		AbstractColumnReference;
		BindExtension;
		MUCItem;
		WeaveDataSource;
		ImageLoaderUtilsEvent;
		MUCOwnerExtension;
		Room;
		NormalizedColumn;
		ProjGauss;
		ProjSterea;
		GeometryColumn;
		DbfRecord;
		ZoomUtils;
		XMPPConnection;
		MUC;
		GreedyLayoutAlgorithm;
		ReferencedColumn;
		IQ;
		DigestMD5;
		FilteredKeySet;
		KeyFilter;
		ProjConstants;
		DataServiceMetadata;
		QKeyManager;
		Type;
		OnEarthProvider;
		OpenMapQuestProvider;
		SecondaryKeyNumColumn;
		NumberColumn;
		DataTableMetadata;
		Base64;
		Bounds2DIndex;
		ShpPolygon;
		Transformation;
		External;
		BIFFVersion;
		RegistrationFieldsEvent;
		ShpPolyline;
		URLRequestUtils;
		XFormat;
		RegisterExtension;
		AttributeColumnCache;
		YahooHybridMapProvider;
		ShpPointZ;
		ImageColumn__missingImageClass;
		LocalAsyncService;
		IncrementalLayoutAlgorithm;
		GridForceDirectedLayout;
		WMSProviders;
		ProjVandg;
		StatisticsCache;
		ProjGstmerc;
		Sheet;
		WMSTile;
		MD5;
		WeaveDataServlet;
		SessionExtension;
		EqualIntervalBinningDefinition;
		DisconnectionEvent;
		Proj4as;
		GeometryStreamDecoder;
		NearestNeighborLayoutAlgorithm;
		BinaryUtil;
		Cell;
		KeySet;
		BLGTreeUtils;
		ImageFactory;
		ComputationalGeometryUtils;
		WFSDataSource;
		AsyncServiceQueue;
		BLGNode;
		WeaveReport;
		ProjMerc;
		AMF3Servlet;
		ForceDirectedLayout;
		HierarchyColumnReference;
		EventUtils;
		ModestMapsWMS;
		DbfField;
		StringLookup;
		ProjEqc;
		ShpFileReader;
		ProjOrtho;
		ObjectPool;
		XIFFErrorEvent;
		Hex;
		FarStream;
		BlueMarbleMapProvider;
		GraphEdge;
		ColorRamp_ColorRampPresetsXML;
		SortedColumn;
		VectorUtils;
		DbfTools;
		BinnedColumn;
		Formula;
		HierarchicalClusteringResult;
		FilteredColumn;
		ProjStere;
		ShpRecord;
		LoginEvent;
		YahooAerialMapProvider;
		PopUpUtils;
		RosterItem;
		ProjSoMerc;
		KDTree;
		FarItem;
		BIFFWriter;
		PingExtension;
		WeavePDBServlet;
		CSVParser;
		JQueryCaller;
		CSSUtils;
		MercatorProjection;
		ColumnUtils;
		Presence;
		ProjLcc;
		ImageColumn;
		DbfError;
		RegistrationSuccessEvent;
		Functions;
		StringDataFilter;
		CSVColumn;
		DynamicKeySet;
		QuantileBinningDefinition;
		AttributeHierarchy;
		StringLookupColumn;
		LinkableBounds2D;
		ProjUtm;
		OnEarthProvider__tileRequestClass;
		StandardDeviationBinningDefinition;
		// WeaveUISpark
		AbstractPlotter;
		AbstractGlyphPlotter;
		SimpleGlyphPlotter;
		_InitializeWeaveUISpark;
		VisToolGroup;
		AnchorPlotter;
		CircleGlyphPlotter;
		CompoundBarChartPlotter;
		BusyIndicator;
		CustomContextMenuManager;
		LinkableDropShadowFilter;
		InteractionController;
		MeterPlotter;
		GaugePlotter;
		RadialAxis;
		BoundsPlotter;
		LinePlotter;
		RegressionLinePlotter;
		WMSPlotter;
		TextGlyphPlotter;
		LinkableTextFormat;
		PieChartHistogramPlotter;
		Visualization;
		ImageGlyphPlotter;
		GridLinePlotter;
		TickMarkUtils;
		PlotTask;
		SimpleAxisPlotter;
		LayerSettings;
		ResultUtils;
		SolidFillStyle;
		ExtendedFillStyle;
		AxisLabelPlotter;
		EditorManager;
		BitmapText;
		LinkableEventListener;
		CirclePlotter;
		ParallelCoordinatesPlotter;
		PlotUtils;
		Weave;
		CompoundRadVizPlotter;
		RamachandranBackgroundPlotter;
		FontLoader;
		InteractiveVisualization;
		SingleImagePlotter;
		BitmapUtils;
		LinkableGlowFilter;
		ColorBinLegendPlotter;
		RadVizPlotter;
		Histogram2DPlotter;
		RectanglePlotter;
		SimpleInteractiveVisualization;
		SizeBinLegendPlotter;
		DynamicFillStyle;
		DrawUtils;
		DynamicLineStyle;
		SolidLineStyle;
		ProbeLinePlotter;
		SpatialIndex;
		GeometryPlotter;
		GraphPlotter;
		ExtendedLineStyle;
		ThermometerPlotter;
		PieChartPlotter;
		AxisPlotter;
		HistogramPlotter;
		PlotterUtils;
		WedgePlotter;
		AnchorPoint;
		PlotManager;
		GraphLabelPlotter;
		WeaveProperties;
		StickFigureGlyphPlotter;
		CustomCursorManager;
		ProbeTextUtils;
		PenTool;
		ScatterPlotPlotter;
		GeometryLabelPlotter;
		LegendUtils;
		BarChartLegendPlotter;
		WeaveWordlePlotter;
	}
}
