/**
 * Generated by Apache Flex Cross-Compiler from weavejs\core\ChildListCallbackInterface.as
 * weavejs.core.ChildListCallbackInterface
 *
 * @fileoverview
 *
 * @suppress {checkTypes}
 */

goog.provide('weavejs.core.ChildListCallbackInterface');

goog.require('weavejs.core.CallbackCollection');
goog.require('weavejs.api.core.IChildListCallbackInterface');
goog.require('weavejs.api.core.ILinkableObject');



/**
 * @constructor
 * @extends {weavejs.core.CallbackCollection}
 * @implements {weavejs.api.core.IChildListCallbackInterface}
 */
weavejs.core.ChildListCallbackInterface = function() {
  weavejs.core.ChildListCallbackInterface.base(this, 'constructor', org.apache.flex.utils.Language.closure(this.setCallbackVariables, this, 'setCallbackVariables'));
};
goog.inherits(weavejs.core.ChildListCallbackInterface, weavejs.core.CallbackCollection);


/**
 * @private
 * @type {string}
 */
weavejs.core.ChildListCallbackInterface.prototype._lastNameAdded = null;


/**
 * @private
 * @type {weavejs.api.core.ILinkableObject}
 */
weavejs.core.ChildListCallbackInterface.prototype._lastObjectAdded = null;


/**
 * @private
 * @type {string}
 */
weavejs.core.ChildListCallbackInterface.prototype._lastNameRemoved = null;


/**
 * @private
 * @type {weavejs.api.core.ILinkableObject}
 */
weavejs.core.ChildListCallbackInterface.prototype._lastObjectRemoved = null;


/**
 * This function will set the list callback variables:
 *     lastNameAdded, lastObjectAdded, lastNameRemoved, lastObjectRemoved, childListChanged
 * @asparam name This is the name of the object that was just added or removed from the hash map.
 * @asparam objectAdded This is the object that was just added to the hash map.
 * @asparam objectRemoved This is the object that was just removed from the hash map.
 * @private
 * @param {string=} name
 * @param {weavejs.api.core.ILinkableObject=} objectAdded
 * @param {weavejs.api.core.ILinkableObject=} objectRemoved
 */
weavejs.core.ChildListCallbackInterface.prototype.setCallbackVariables = function(name, objectAdded, objectRemoved) {
  name = typeof name !== 'undefined' ? name : null;
  objectAdded = typeof objectAdded !== 'undefined' ? objectAdded : null;
  objectRemoved = typeof objectRemoved !== 'undefined' ? objectRemoved : null;
  this._lastNameAdded = objectAdded ? name : null;
  this._lastObjectAdded = objectAdded;
  this._lastNameRemoved = objectRemoved ? name : null;
  this._lastObjectRemoved = objectRemoved;
};


/**
 * This function will run callbacks immediately, setting the list callback variables before each one.
 * @asparam name
 * @asparam objectAdded
 * @asparam objectRemoved
 * @export
 * @param {string} name
 * @param {weavejs.api.core.ILinkableObject} objectAdded
 * @param {weavejs.api.core.ILinkableObject} objectRemoved
 */
weavejs.core.ChildListCallbackInterface.prototype.runCallbacks = function(name, objectAdded, objectRemoved) {
  var /** @type {string} */ _name = this._lastNameAdded || this._lastNameRemoved;
  var /** @type {weavejs.api.core.ILinkableObject} */ _added = this._lastObjectAdded;
  var /** @type {weavejs.api.core.ILinkableObject} */ _removed = this._lastObjectRemoved;
  this._runCallbacksImmediately(name, objectAdded, objectRemoved);
  this.setCallbackVariables(_name, _added, _removed);
};


Object.defineProperties(weavejs.core.ChildListCallbackInterface.prototype, /** @lends {weavejs.core.ChildListCallbackInterface.prototype} */ {
/** @export */
lastNameAdded: {
get: /** @this {weavejs.core.ChildListCallbackInterface} */ function() {
  return this._lastNameAdded;
}},
/** @export */
lastObjectAdded: {
get: /** @this {weavejs.core.ChildListCallbackInterface} */ function() {
  return this._lastObjectAdded;
}},
/** @export */
lastNameRemoved: {
get: /** @this {weavejs.core.ChildListCallbackInterface} */ function() {
  return this._lastNameRemoved;
}},
/** @export */
lastObjectRemoved: {
get: /** @this {weavejs.core.ChildListCallbackInterface} */ function() {
  return this._lastObjectRemoved;
}}}
);


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
weavejs.core.ChildListCallbackInterface.prototype.FLEXJS_CLASS_INFO = { names: [{ name: 'ChildListCallbackInterface', qName: 'weavejs.core.ChildListCallbackInterface'}], interfaces: [weavejs.api.core.IChildListCallbackInterface] };
