/**
 * Generated by Apache Flex Cross-Compiler from weavejs\core\LinkableNumber.as
 * weavejs.core.LinkableNumber
 *
 * @fileoverview
 *
 * @suppress {checkTypes}
 */

goog.provide('weavejs.core.LinkableNumber');

goog.require('weavejs.core.LinkableVariable');



/**
 * @constructor
 * @extends {weavejs.core.LinkableVariable}
 * @param {number=} defaultValue
 * @param {Function=} verifier
 * @param {boolean=} defaultValueTriggersCallbacks
 */
weavejs.core.LinkableNumber = function(defaultValue, verifier, defaultValueTriggersCallbacks) {
  defaultValue = typeof defaultValue !== 'undefined' ? defaultValue : NaN;
  verifier = typeof verifier !== 'undefined' ? verifier : null;
  defaultValueTriggersCallbacks = typeof defaultValueTriggersCallbacks !== 'undefined' ? defaultValueTriggersCallbacks : true;
  weavejs.core.LinkableNumber.base(this, 'constructor', Number, verifier, arguments.length ? defaultValue : undefined, defaultValueTriggersCallbacks);
};
goog.inherits(weavejs.core.LinkableNumber, weavejs.core.LinkableVariable);


/**
 * @export
 * @override
 */
weavejs.core.LinkableNumber.prototype.getSessionState = function() {
  return Number(this._sessionStateExternal);
};


/**
 * @export
 * @override
 */
weavejs.core.LinkableNumber.prototype.setSessionState = function(value) {
  if (!org.apache.flex.utils.Language.is(value, Number)) {
    if (value == null || value === '')
      value = NaN;
    else
      value = Number(value);
  }
  weavejs.core.LinkableNumber.base(this, 'setSessionState', value);
};


/**
 * @protected
 * @override
 */
weavejs.core.LinkableNumber.prototype.sessionStateEquals = function(otherSessionState) {
  if (this._sessionStateInternal === null)
    this._sessionStateInternal = this._sessionStateExternal = NaN;
  if (isNaN(this._sessionStateInternal) && isNaN(otherSessionState))
    return true;
  return this._sessionStateInternal == otherSessionState;
};


Object.defineProperties(weavejs.core.LinkableNumber.prototype, /** @lends {weavejs.core.LinkableNumber.prototype} */ {
/** @export */
value: {
get: /** @this {weavejs.core.LinkableNumber} */ function() {
  return this._sessionStateExternal;
},
set: /** @this {weavejs.core.LinkableNumber} */ function(value) {
  this.setSessionState(value);
}}}
);


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
weavejs.core.LinkableNumber.prototype.FLEXJS_CLASS_INFO = { names: [{ name: 'LinkableNumber', qName: 'weavejs.core.LinkableNumber'}] };
