/**
 * Generated by Apache Flex Cross-Compiler from weavejs\core\LinkableString.as
 * weavejs.core.LinkableString
 *
 * @fileoverview
 *
 * @suppress {checkTypes}
 */

goog.provide('weavejs.core.LinkableString');

goog.require('weavejs.core.LinkableVariable');



/**
 * @constructor
 * @extends {weavejs.core.LinkableVariable}
 * @param {string=} defaultValue
 * @param {Function=} verifier
 * @param {boolean=} defaultValueTriggersCallbacks
 */
weavejs.core.LinkableString = function(defaultValue, verifier, defaultValueTriggersCallbacks) {
  defaultValue = typeof defaultValue !== 'undefined' ? defaultValue : null;
  verifier = typeof verifier !== 'undefined' ? verifier : null;
  defaultValueTriggersCallbacks = typeof defaultValueTriggersCallbacks !== 'undefined' ? defaultValueTriggersCallbacks : true;
  weavejs.core.LinkableString.base(this, 'constructor', String, verifier, arguments.length ? defaultValue : undefined, defaultValueTriggersCallbacks);
};
goog.inherits(weavejs.core.LinkableString, weavejs.core.LinkableVariable);


/**
 * @export
 * @override
 */
weavejs.core.LinkableString.prototype.setSessionState = function(value) {
  if (value != null)
    value = String(value);
  weavejs.core.LinkableString.base(this, 'setSessionState', value);
};


Object.defineProperties(weavejs.core.LinkableString.prototype, /** @lends {weavejs.core.LinkableString.prototype} */ {
/** @export */
value: {
get: /** @this {weavejs.core.LinkableString} */ function() {
  return this._sessionStateExternal;
},
set: /** @this {weavejs.core.LinkableString} */ function(value) {
  this.setSessionState(value);
}}}
);


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
weavejs.core.LinkableString.prototype.FLEXJS_CLASS_INFO = { names: [{ name: 'LinkableString', qName: 'weavejs.core.LinkableString'}] };
