/**
 * Generated by Apache Flex Cross-Compiler from weavejs\core\LinkableCallbackScript.as
 * weavejs.core.LinkableCallbackScript
 *
 * @fileoverview
 *
 * @suppress {checkTypes}
 */

goog.provide('weavejs.core.LinkableCallbackScript');

goog.require('weavejs.Weave');
goog.require('weavejs.WeaveAPI');
goog.require('weavejs.core.LinkableBoolean');
goog.require('weavejs.core.LinkableHashMap');
goog.require('weavejs.core.LinkableString');
goog.require('weavejs.api.core.ICallbackCollection');
goog.require('weavejs.api.core.ILinkableObject');



/**
 * @constructor
 * @implements {weavejs.api.core.ILinkableObject}
 */
weavejs.core.LinkableCallbackScript = function() {
  var /** @type {weavejs.api.core.ICallbackCollection} */ callbacks = weavejs.WeaveAPI.SessionManager.getCallbackCollection(this);
  callbacks.addImmediateCallback(null, org.apache.flex.utils.Language.closure(this._immediateCallback, this, '_immediateCallback'));
  callbacks.addGroupedCallback(null, org.apache.flex.utils.Language.closure(this._groupedCallback, this, '_groupedCallback'));
};


/**
 * @export
 * @const
 * @type {weavejs.core.LinkableHashMap}
 */
weavejs.core.LinkableCallbackScript.prototype.variables = weavejs.Weave.registerLinkableChild(this, new weavejs.core.LinkableHashMap());


/**
 * @export
 * @const
 * @type {weavejs.core.Linkablestring}
 */
weavejs.core.LinkableCallbackScript.prototype.script = weavejs.Weave.registerLinkableChild(this, new weavejs.core.LinkableString());


/**
 * @export
 * @const
 * @type {weavejs.core.LinkableBoolean}
 */
weavejs.core.LinkableCallbackScript.prototype.delayWhileBusy = weavejs.Weave.registerLinkableChild(this, new weavejs.core.LinkableBoolean(true));


/**
 * @export
 * @const
 * @type {weavejs.core.LinkableBoolean}
 */
weavejs.core.LinkableCallbackScript.prototype.groupedCallback = weavejs.Weave.registerLinkableChild(this, new weavejs.core.LinkableBoolean(true));


/**
 * @export
 * @param {string} variableName
 * @return {weavejs.api.core.ILinkableObject}
 */
weavejs.core.LinkableCallbackScript.prototype.get = function(variableName) {
  return this.variables.getObject(variableName);
};


/**
 * @private
 */
weavejs.core.LinkableCallbackScript.prototype._immediateCallback = function() {
  if (!this.groupedCallback.value)
    this._runScript();
};


/**
 * @private
 */
weavejs.core.LinkableCallbackScript.prototype._groupedCallback = function() {
  if (this.groupedCallback.value)
    this._runScript();
};


/**
 * @private
 */
weavejs.core.LinkableCallbackScript.prototype._runScript = function() {
  if (this.delayWhileBusy.value && weavejs.WeaveAPI.SessionManager.linkableObjectIsBusy(this))
    return;
  if (!this.script.value)
    return;
  try {
    weavejs.Weave.global.eval.apply(this, this.script.value);
  } catch (e) {
    weavejs.Weave.error(e);
  }
};


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
weavejs.core.LinkableCallbackScript.prototype.FLEXJS_CLASS_INFO = { names: [{ name: 'LinkableCallbackScript', qName: 'weavejs.core.LinkableCallbackScript'}], interfaces: [weavejs.api.core.ILinkableObject] };
