/**
 * Generated by Apache Flex Cross-Compiler from weavejs\core\LogEntry.as
 * weavejs.core.LogEntry
 *
 * @fileoverview
 *
 * @suppress {checkTypes}
 */

goog.provide('weavejs.core.LogEntry');



/**
 * This is an entry in the session history log.  It contains both undo and redo session state diffs.
 * The triggerDelay is the time it took for the user to make a change since the last synchronization.
 * This time difference does not include the time it took to set the session state.  This way, when
 * the session state is replayed at a reasonable speed regardless of the speed of the computer.
 * @asparam id
 * @asparam forward The diff for applying redo.
 * @asparam backward The diff for applying undo.
 * @asparam triggerDelay The length of time between the last synchronization and the diff.
 * @constructor
 * @param {number} id
 * @param {Object} forward
 * @param {Object} backward
 * @param {number} triggerDelay
 * @param {number} diffDuration
 */
weavejs.core.LogEntry = function(id, forward, backward, triggerDelay, diffDuration) {
  this.id = id;
  this.forward = forward;
  this.backward = backward;
  this.triggerDelay = triggerDelay;
  this.diffDuration = diffDuration;
};


/**
 * @export
 * @type {number}
 */
weavejs.core.LogEntry.prototype.id;


/**
 * @export
 * @type {Object}
 */
weavejs.core.LogEntry.prototype.forward;


/**
 * @export
 * @type {Object}
 */
weavejs.core.LogEntry.prototype.backward;


/**
 * @export
 * @type {number}
 */
weavejs.core.LogEntry.prototype.triggerDelay;


/**
 * @export
 * @type {number}
 */
weavejs.core.LogEntry.prototype.diffDuration;


/**
 * This will convert an Array of generic objects to an Array of LogEntry objects.
 * Generic objects are easier to create backwards compatibility for.
 * @export
 * @param {Array} array
 * @param {number} defaultTriggerDelay
 * @return {Array}
 */
weavejs.core.LogEntry.convertGenericObjectsToLogEntries = function(array, defaultTriggerDelay) {
  for (var /** @type {number} */ i = 0; i < array.length; i++) {
    var /** @type {Object} */ o = array[i];
    if (!org.apache.flex.utils.Language.is(o, weavejs.core.LogEntry))
      array[i] = new weavejs.core.LogEntry(o.id, o.forward, o.backward, o.triggerDelay || defaultTriggerDelay, o.diffDuration);
  }
  return array;
};


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
weavejs.core.LogEntry.prototype.FLEXJS_CLASS_INFO = { names: [{ name: 'LogEntry', qName: 'weavejs.core.LogEntry'}] };
