/**
 * Generated by Apache Flex Cross-Compiler from WeaveJS.as
 * WeaveJS
 *
 * @fileoverview
 *
 * @suppress {checkTypes}
 */

goog.provide('WeaveJS');

goog.require('weavejs.Weave');



/**
 * @constructor
 */
WeaveJS = function() {
};


/**
 * @export
 */
WeaveJS.prototype.start = function() {
  weavejs.Weave.global.Weave = weavejs.Weave;
};


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
WeaveJS.prototype.FLEXJS_CLASS_INFO = { names: [{ name: 'WeaveJS', qName: 'WeaveJS'}] };
