/**
 * Generated by Apache Flex Cross-Compiler from weavejs\WeaveAPI.as
 * weavejs.WeaveAPI
 *
 * @fileoverview
 *
 * @suppress {checkTypes}
 */

goog.provide('weavejs.WeaveAPI');

goog.require('weavejs.core.ClassRegistryImpl');
goog.require('weavejs.api.core.IClassRegistry');
goog.require('weavejs.api.core.ILocaleManager');
goog.require('weavejs.api.core.IProgressIndicator');
goog.require('weavejs.api.core.ISessionManager');



/**
 * @constructor
 */
weavejs.WeaveAPI = function() {
};


/**
 * @export
 * @const
 * @type {number}
 */
weavejs.WeaveAPI.TASK_PRIORITY_IMMEDIATE = 0;


/**
 * @export
 * @const
 * @type {number}
 */
weavejs.WeaveAPI.TASK_PRIORITY_HIGH = 1;


/**
 * @export
 * @const
 * @type {number}
 */
weavejs.WeaveAPI.TASK_PRIORITY_NORMAL = 2;


/**
 * @export
 * @const
 * @type {number}
 */
weavejs.WeaveAPI.TASK_PRIORITY_LOW = 3;


/**
 * @private
 * @type {weavejs.core.ClassRegistryImpl}
 */
weavejs.WeaveAPI._classRegistry = null;


/**
 * @export
 * @type {Object}
 */
weavejs.WeaveAPI.StageUtils;Object.defineProperties(weavejs.WeaveAPI, /** @lends {weavejs.WeaveAPI} */ {
/** @export */
ClassRegistry: {
get: function() {
  if (!weavejs.WeaveAPI._classRegistry)
    weavejs.WeaveAPI._classRegistry = new weavejs.core.ClassRegistryImpl();
  return weavejs.WeaveAPI._classRegistry;
}},
/** @export */
SessionManager: {
get: function() {
  return (weavejs.WeaveAPI._classRegistry || weavejs.WeaveAPI.ClassRegistry).singletonInstances[weavejs.api.core.ISessionManager] || weavejs.WeaveAPI._classRegistry.getSingletonInstance(weavejs.api.core.ISessionManager);
}},
/** @export */
ProgressIndicator: {
get: function() {
  return (weavejs.WeaveAPI._classRegistry || weavejs.WeaveAPI.ClassRegistry).singletonInstances[weavejs.api.core.IProgressIndicator] || weavejs.WeaveAPI._classRegistry.getSingletonInstance(weavejs.api.core.IProgressIndicator);
}},
/** @export */
LocaleManager: {
get: function() {
  return (weavejs.WeaveAPI._classRegistry || weavejs.WeaveAPI.ClassRegistry).singletonInstances[weavejs.api.core.ILocaleManager] || weavejs.WeaveAPI._classRegistry.getSingletonInstance(weavejs.api.core.ILocaleManager);
}}}
);


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
weavejs.WeaveAPI.prototype.FLEXJS_CLASS_INFO = { names: [{ name: 'WeaveAPI', qName: 'weavejs.WeaveAPI'}] };
