/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ntlm_SSPIJNIClient */

#ifndef _Included_ntlm_SSPIJNIClient
#define _Included_ntlm_SSPIJNIClient
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: initialized */
/*
 * Class:     ntlm_SSPIJNIClient
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_sourceforge_jtds_util_SSPIJNIClient_initialize
  (JNIEnv *, jobject);

/*
 * Class:     ntlm_SSPIJNIClient
 * Method:    unInitialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_sourceforge_jtds_util_SSPIJNIClient_unInitialize
  (JNIEnv *, jobject);

/*
 * Class:     ntlm_SSPIJNIClient
 * Method:    prepareSSORequest
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_sourceforge_jtds_util_SSPIJNIClient_prepareSSORequest
  (JNIEnv *, jobject);

/*
 * Class:     ntlm_SSPIJNIClient
 * Method:    prepareSSOSubmit
 * Signature: ([BJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_sourceforge_jtds_util_SSPIJNIClient_prepareSSOSubmit
  (JNIEnv *, jobject, jbyteArray, jlong);

#ifdef __cplusplus
}
#endif
#endif
